services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    env_file:
      - .env
    expose:
      - 8000
    command: ["sh", "/app/entrypoint.sh"]


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
    depends_on:
      - web

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Tokyo
      PGTZ: Asia/Tokyo
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
